image: Visual Studio 2017

branches:
    only:
    - master

#来源：https://github.com/madskristensen/ExtensionScripts
install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

#增量版本,更新构建版本
before_build:
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  #- ps: Vsix-TokenReplacement CommentTranslator\source.extension.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'

  #还原包，编译
build_script:
  - nuget restore -Verbosity quiet
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

  #推送到Artifacts，发布到图库
after_test:
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery